FROM ubuntu:hirsute

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
        build-essential \
        cmake \
        git \
        gfortran \
        libopencv-dev \
        qtbase5-dev \
        qtbase5-private-dev \
        libqt5multimedia5 \
        libqt5multimedia5-plugins \
        ca-certificates


# vi: ft=dockerfile
